services:

  # MySQL Database
  memory_db:
    image: mysql:8.0
    container_name: memory_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: memory_db
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: "123456"
    volumes:
      - mysql-data-memory:/var/lib/mysql
    networks:
      - memory_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  # React Frontend
  memory_front:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=https://memory.zennoune.fr/api
    container_name: memory_front
    depends_on:
      - memory_back
    restart: always
    networks:
      - memory_network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      # Frontend Router
      - "traefik.http.routers.memory-front.rule=Host(`memory.zennoune.fr`)"
      - "traefik.http.routers.memory-front.entrypoints=websecure"
      - "traefik.http.routers.memory-front.tls.certresolver=letsencrypt"
      - "traefik.http.services.memory-front.loadbalancer.server.port=80"


  # Java Spring Boot Backend
  memory_back:
    build:
      context: ./backend
    container_name: memory_back
    restart: always
    depends_on:
      memory_db:
        condition: service_healthy
    networks:
      - memory_network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      # Backend Router & API Path Matching
      - "traefik.http.routers.memory-back.rule=Host(`memory.zennoune.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.memory-back.entrypoints=websecure"
      - "traefik.http.routers.memory-back.tls.certresolver=letsencrypt"
      # Spring Boot default internal port 8080
      - "traefik.http.services.memory-back.loadbalancer.server.port=8080"


volumes:
  mysql-data-memory:


networks:
  memory_network:
    name: memory_network
    driver: bridge
  traefik-network:
    external: true